import express from 'express';
import { logger } from '../utils/logger.js';
import config from '../config/index.js';

// Importar las rutas con documentación automática
import authFluentRoutes from '../modules/auth/route/auth.fluent.routes.js';
import userFluentRoutes from '../modules/user/route/user.fluent.routes.js';
import personaFluentRoutes from '../modules/persona/route/persona.fluent.routes.js';

// Importar rutas de desarrollo
import authDevRoutes from '../modules/auth/route/auth.dev.routes.js';

// Crear router principal de la API
const router = express.Router();

// Middleware para logging de rutas API
router.use((req, res, next) => {
  logger.debug(`API Request: ${req.method} ${req.originalUrl}`);
  next();
});

// Cargar las rutas con documentación automática
router.use('/auth', authFluentRoutes);
router.use('/users', userFluentRoutes);
router.use('/personas', personaFluentRoutes);

// Rutas de desarrollo (solo disponibles en NODE_ENV=development)
if (config.env === 'development') {
  router.use('/auth/dev', authDevRoutes);
  logger.info('🚧 Rutas de desarrollo habilitadas en /api/auth/dev/*');
}

// Ruta de información de la API
router.get('/', (req, res) => {
  const endpoints = {
    auth: '/api/auth',
    users: '/api/users',
    personas: '/api/personas',
    docs: '/docs',
    health: '/health'
  };

  // Agregar endpoints de desarrollo si estamos en development
  if (config.env === 'development') {
    endpoints.authDev = '/api/auth/dev';
  }
  res.json({
    message: 'API REST - Proyecto Backend Grupo 06',
    version: '1.0.0',
    environment: config.env,
    timestamp: new Date().toISOString(),
    endpoints,
    status: 'OK',
    documentation: {
      swagger: '/docs',
      autoGenerated: true,
      features: [
        'Mapeo automático de validadores Joi a Swagger',
        'Documentación sincronizada con código',
        'Sin configuración manual de schemas'
      ]
    },
    ...(config.env === 'development' && {
      devInfo: {
        message: 'Entorno de desarrollo activo',
        simplifiedAuth: 'Disponible en /api/auth/dev/* (contraseñas en texto plano)',
        postmanCollection: 'Utiliza los endpoints /dev para testing con Postman'
      }
    })
  });
});

export default router;